### ISSUE TITLE
很遗憾

### ISSUE THREAD

**Issue by NumerHero** [zhui-team/zhui#1]
原以为中国风点进来看了一下，比较失望
建议不要执迷于简单的组件开发，除了了解react 如何搬砖没有其他意义

不知道你是兴趣驱动，还是为了找工作

兴趣使然：
建议多刷刷：
https://tympanus.net/codrops/
https://codepen.io/

找工作
想去BAT的话，要多刷刷算法和数据结构

就酱

**Comment by AddOneDn** [comment]
感谢关注

不知道你从哪看到了这个仓库

我在提起这个项目的时候说到 1是开源 2是学习 当然中国风我也是很喜欢的

这个仓库刚刚搭建几天而已 目前只做了最基础的工作

设计和逻辑之后会大幅度修改的

另外我是科班，算法和数据结构一直有在学习，再次感谢您的建议

**Comment by MuYunyun** [comment]
这个项目想法很棒呀~

**Comment by MuYunyun** [comment]
这个项目想法很棒呀~
