### ISSUE TITLE
进度条属性

### ISSUE THREAD

**Issue by jorgezx** [zhui-team/zhui#12]
想法很好，风格很棒，能有个整体网页的demo就更惊艳了！

进度条有个属性：`precent`，感觉是不是略艺术了...
`percent`？

**Comment by dxiaoqi** [comment]
因为组件是单独设计的，再设计会考虑到整体的一些美感，也会有一个demo页面的，争取把文档用这些组件重写

**Comment by AddOneDn** [comment]
感谢提出 是单词拼写错误😭 已修改
