### ISSUE TITLE
简直瞎搞，作者根本不了解“中国风”。

### ISSUE THREAD

**Issue by AibiTi** [zhui-team/zhui#13]
不是搞一些颜色，搞一些灯笼，搞一些对联就是“中国风”，明显的以“中国风”为势头，骗星行为。

**Comment by dxiaoqi** [comment]
我们只是学生，对于中国风的精髓领悟不够，我们只是单纯对于中国风的热爱，以当下的领悟与能力来表达，如果您觉得我们是骗星，我在此致以抱歉，所以也希望可以对中国风有深入了解的提出意见，我们会虚心接受与学习

**Comment by bigmeow** [comment]
我看不下去了，楼上这个人就是个喷子，作者无需理会，既然喷子跑出来了，我们就来看一下这个喷子的战绩：
首先这个人fock了一堆知名库置顶在自己的主页上，假装自己很牛逼，咋一看好像参与了这么多知名开源项目，其实啥都没有；
接下来我们看一下她（他）的个人主页里的动态，看看这喷子的动态：

![image](https://user-images.githubusercontent.com/10484248/55679072-2deb9d00-5937-11e9-9e32-9761684f4554.png)

![image](https://user-images.githubusercontent.com/10484248/55679075-4e1b5c00-5937-11e9-8d95-e5b20cf7b5ac.png)

![image](https://user-images.githubusercontent.com/10484248/55679082-9b97c900-5937-11e9-9c98-6ff8f906719a.png)
![image](https://user-images.githubusercontent.com/10484248/55679085-b0745c80-5937-11e9-8144-f16df1727258.png)

连开源库的名字都能喷一下。

综上所述，这个号的存在就是为了喷而存在，并且这种人是那种看了种子资源也不愿意说声“楼主好人一生平安”的奇葩存在，我为中国有这种喷子“程序员”默哀三分钟

**Comment by AddOneDn** [comment]
你好，我是作者之一，我收回我的小伙伴对你的抱歉，我觉得你就是个傻B，请滚。

**Comment by AibiTi** [comment]
@bigmeow 喷你妹，我就问一下为什么是这个名字，操你妈。

**Comment by bigmeow** [comment]
为了不给其他人造成困扰，我后面不会再回复这个issue, 对于正确指出批评并提供意见的人，相信做开源库的都有这个胸怀接受，而为了自己舒服把反馈区当成“评论区”大放厥词以打击作者心态的人，我一向零容忍，当然我这是第一次在github遇到你这样的。
我向来不以最坏的恶意揣测他人尤其还是同行，不过我看了你的动态后，很遗憾你一直在给他人制造“情绪垃圾”，我不了解你也无法用它来评判你的人品，不管你是有意还是无心，在我眼里，你就是个喷子，请手留点手得，愿你记得你的键盘是用来写代码吃饭的。
[个人中心最下角删除帐号按钮](https://github.com/settings/admin) 祝走好，不送。
@AibiTi

**Comment by AibiTi** [comment]
@bigmeow 你才是喷子，写这么多字，天天草泥马。

**Comment by AibiTi** [comment]
@bigmeow 垃圾，草你吗！
