### ISSUE TITLE
    TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'

### ISSUE THREAD

**Issue by j710328466** [zhui-team/zhui#15]
拉取之后的 jest 测试会报错，初步判断是node版本问题，
在v11.11不行，在v11.10正常

**Comment by dxiaoqi** [comment]
收到(｡>ㅿ<｡)，感谢反馈

**Comment by AddOneDn** [comment]
[TypeError: Cannot assign to read only...](https://github.com/facebook/jest/issues/8069)
查了一下，应该是 v11.11 和 jest 的问题，建议换到 v11.10 及以下版本。
目前本人的开发的环境是v10.15.3 ~
再次感谢反馈！
