### ISSUE TITLE
WaterMark报错，在zhui中找不到

### ISSUE THREAD

**Issue by ChinaLiuRixing** [zhui-team/zhui#19]
解决方案：打开node_modules/zhui/esm/index.js
追加一行export { default as WaterMark } from './watermark';

关闭server，然后重新npm start即可

**Comment by AddOneDn** [comment]
感谢反馈，目前WaterMark组件仍处于实验阶段，还未打算投入使用，但是却展示在了文档中
很抱歉由于本人文档的疏忽给您带来了不便

**Comment by ChinaLiuRixing** [comment]
我比较关注你们 所以多了两句嘴 嘿嘿

**Comment by AddOneDn** [comment]
很感谢大佬的关注~ 我们会一直维护下去的
