### ISSUE TITLE
很棒噢，看着很舒服，很有味道

### ISSUE THREAD

**Issue by YunJingJian** [zhui-team/zhui#20]
考虑一下出别的框架版本吗？或者单独抽出css做样式库

**Comment by AddOneDn** [comment]
抱歉哈，由于本人精力有限及技术能力限制，可能没有足够的时间达到您的要求。
很感谢您对这个仓库的喜爱，如果您或者周围的朋友感兴趣的话，欢迎使用其他框架来实现这个库~
