### ISSUE TITLE
[bug report]直接输入子域名，跳转notfound

### ISSUE THREAD

**Issue by YutHelloWorld** [zhui-team/zhui#3]
![image](https://user-images.githubusercontent.com/20860159/55303492-2af53600-5479-11e9-9507-ba075b2b6ca6.png)
可以加个404.html 跳回index.html

**Comment by AddOneDn** [comment]
O__O "… 这个是自动部署在netlify上的 我也不清楚怎么会这样.. 我下午看看可不可以调整

**Comment by AddOneDn** [comment]
应该是部署网站的问题，后期我会更换到自己的服务器😊
